### PR TITLE
Add deterministic classnames for styled-components

### PR DESCRIPTION
**Pull request by koenajv**
Non-deterministic classnames put a huge burden on any server-side rendered apps, as the string object will keep filling up for every page request (due to the pseudo-random generation of classNames). 

This PR:
*  adds a babel-plugin that fixes this issue, leading to deterministic classnames and as such reducing the amount of memory used in long-lived applications (i.e. mostly on SSR)
* rewrites `.extend` to styled(YourComponent) so as to make sure that the babel-plugin picks them up (this doesn't work for the "legacy" api that extend is)
* removes the package-lock.json as we generally use yarn.lock and we shouldn't have both
* Upgrades to React 16.9 as needed for Styled Components 5.
* Upgrades all packages (Docz etc.) to work with React 16.9.

Read more:
https://styled-components.com/docs/advanced#server-side-rendering
https://styled-components.com/docs/api#deprecated-extend
https://medium.com/styled-components/announcing-styled-components-v5-beast-mode-389747abd987

### CODE REVIEW

**Comment by brunoqueiros** [comment]
For some reason, the preview page does not work on this branch.

image

**Comment by koenajv** [comment]
> For some reason, the preview page does not work on this branch.
> 
> image

👋Welcome back 😄

Yea I saw this too. I'll look into it further when I pick this back up, probably next week or so. Unless you've found the cause already?

**Comment by abt6595819374th** [comment]
Some components are off / broken:

- https://deploy-preview-186--zealous-lumiere-8dc855.netlify.com/Base/Base is broken (vs https://zealous-lumiere-8dc855.netlify.com/Base/Base)

- Text font-size and color are different https://deploy-preview-186--zealous-lumiere-8dc855.netlify.com/Bootstrap/Container vs https://deploy-preview-186--zealous-lumiere-8dc855.netlify.com/Bootstrap/Container 

- https://deploy-preview-186--zealous-lumiere-8dc855.netlify.com/Base/Pressable#anchor-like-button It seems that Docz started escaping html entities. Here it prints out `&nbsp;`.

- Input width/paddings have changed, so they look broken https://deploy-preview-186--zealous-lumiere-8dc855.netlify.com/Forms/Input#with-placeholder-to-the-right. Dropdown of an input with autosuggestions goes under the input https://deploy-preview-186--zealous-lumiere-8dc855.netlify.com/Forms/Input#with-autosuggestions

Not sure if these should be fixed or maybe removed? E.g. do we use inputs with autosuggestions? Maybe it's not worth it fixing it?

**Comment by koenajv** [comment]
@abt6595819374th Thanks for the thorough check. Considering we're not actively using Docz anymore I'd say it does not need to be perfect, as the components do work as they should in runtime. The reason why the preview doesn't work properly is because between Docz 0.x and 2.x a lot has changed w.r.t. theming. 

However, I've addressed some of the major points you named, mainly by making `Wrapper` work again (it no longer works to pass a wrapper as a prop to <Playground>, so I'm now just composing it with plain JSX). The only things that are different now are some spacing things (the playground does not have spacing in the new version) and the `&nbsp` thing.

**Pull request merged**
